include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

obj-y += $(curr)/mtk_platform_common.o
obj-y += $(curr)/mtk_gpu_dvfs.o
ifeq ($(CONFIG_MTK_GPU_MFG_COUNTER),y)
ifeq ($(MTK_GPU_VERSION),mali bifrost r49p1)
$(error MTK_GPU_MFG_COUNTER uses a Gator HWCNT API removed from Mali r49p1)
endif
endif
obj-$(CONFIG_MTK_GPU_MFG_COUNTER) += $(curr)/mtk_mfg_counter.o
obj-y += $(curr)/mtk_gpu_power_sspm_ipi.o

ccflags-y += -I$(srctree)/drivers/devfreq/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/swpm_v1/
